//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalHistory
    {
        public decimal Pkid { get; set; }
        public Nullable<decimal> Entitytype { get; set; }
        public Nullable<decimal> Status { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> isactive { get; set; }
        public string EntityCode { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> Updateddate { get; set; }
    }
}
