//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankingDetail
    {
        public decimal id { get; set; }
        public string merchantid { get; set; }
        public string accountnumber { get; set; }
        public string acctype { get; set; }
        public string ifsccode { get; set; }
        public Nullable<decimal> bankid { get; set; }
        public Nullable<System.DateTime> Validfrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public byte[] ChequeDetails { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Entitytype { get; set; }

        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }
    }
}
