//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConcessionaireServiceRequest
    {
        public decimal id { get; set; }
        public string ServiceRequestId { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string VehicleDetails { get; set; }
        public Nullable<System.DateTime> WalletCreationTime { get; set; }
        public string GroupName { get; set; }
        public string CompanyName { get; set; }
        public string WalletId { get; set; }
        public string WalletVehicleCount { get; set; }
        public string WalletOwnerName { get; set; }
        public string ContactNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> CustomerType { get; set; }
        public Nullable<decimal> RequestType { get; set; }
        public Nullable<decimal> Priority { get; set; }
        public Nullable<decimal> RequestSubType { get; set; }
        public Nullable<decimal> VerificationMode { get; set; }
        public string Remarks { get; set; }
        public string MerchantId { get; set; }
        public string SubMerchantID { get; set; }
        public string OTPNumber { get; set; }
        public string DocumentPath { get; set; }
        public Nullable<decimal> Status { get; set; }
    }
}
