//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigrationMaster
    {
        public decimal Configid { get; set; }
        public string ConfigurationDescription { get; set; }
        public string ConfigurationName { get; set; }
        public Nullable<decimal> Configcategory { get; set; }
        public Nullable<decimal> ConfigType { get; set; }
        public Nullable<decimal> ConfigValueType { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Configvalue { get; set; }
        public Nullable<decimal> AppDesc { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }


        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }
    }
}
