//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public decimal Relation_ID { get; set; }
        public decimal entitytype { get; set; }
        public string DocumentName { get; set; }


        public int countryID { get; set; }
        public decimal Org_ID { get; set; }
        public string Document_Name { get; set; }
        public bool Mandatory { get; set; }
        

        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }
    }
}
