//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;

    public partial class FileUpload
    {
        public int FileID { get; set; }
        public string VendorCode { get; set; }
        public string FileName { get; set; }
        public byte FileUploaded { get; set; }
        public string FileType { get; set; }
        public string Size { get; set; }
        public string FilePath { get; set; }

        public string DocType { get; set; }

        public string DocName { get; set; }

        public DateTime ExpiryDate { get; set; }

        public Boolean IsMandatory { get; set; }
        public string LoginEmailId { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Boolean Flag { get; set; }

        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }
    }
}
