



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;

    public partial class InviteSupplier
    {

        public string PurOrgCode { get; set; }        
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public string ContactNo { get; set; }
        public string EmailAddress { get; set; }

        //public string PurchasingOrgName { get; set; }

        //public string PurchasingOrgID { get; set; }
        public string Invitedby { get; set; }
        


        ///public string LoginEmailID { get; set; }

        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }
    }
}
