
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;

    public partial class Invoice
    {
        public int SrNo { get; set; }
        public string VendorCode { get; set; }
        public string Company { get; set; }
        public string InvoiceNumber { get; set; }
        public string InvoiceAccount { get; set; }
        public string VendorName { get; set; }
        public string VendorAccount { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string PostingDate { get; set; }
        public string InvoiceDate { get; set; }
        public string InvoiceDescription { get; set; }
        public string Currency { get; set; }
        public string Loged { get; set; }
        public string ErrorMessage { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public string Linereference { get; set; }

        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }
    }
}

