//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupValue
    {
        public int CodeType { get; set; }
        //public int Code { get; set; }
        public string CodeDesc { get; set; }
        public string RefCode { get; set; }
        //public bool SecYN { get; set; }
        //public string Description1 { get; set; }
        //public string Description2 { get; set; }
        //public string Description3 { get; set; }
        //public string Description4 { get; set; }
        //public Nullable<System.DateTime> LastModifiedDate { get; set; }
        //public string LastModifiedUser { get; set; }
        //public string Remarks { get; set; }
        //public int OrganisationID { get; set; }

        //vinod added 17-4-2021
        public string ModeFlag { get; set; }
        public string LoginEmailId { get; set; }
        public string Country { get; set; }


        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }
    }
}
