//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup
    {
        public int OrganisationId { get; set; }
        public int CodeType { get; set; }
        public string CodeTypeDesc { get; set; }
        public bool CodeSec { get; set; }
        public string TypeOfLookup { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedUser { get; set; }
        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }



        //Country fields
        public string QLAND { get; set; }
        public string QLTXT { get; set; }

        //Title fields
        public string TITLE { get; set; }
        public string TITLE_MEDI { get; set; }

        //Organisation_Type fields
        public int Org_Id { get; set; }
        public string Org_Type { get; set; }

        //Region fields
        public int RegionId { get; set; }
        public string descr { get; set; }

        //Sourcing_Category fields
        public string SupplierCatId { get; set; }
        public string SupplierCategory { get; set; }
    }
}
