//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainMenu
    {
        public int Id { get; set; }
        public string MainMenuName { get; set; }
        public Nullable<decimal> MenuOrder { get; set; }
        public Nullable<decimal> ServicesID { get; set; }
        public string ModuleName { get; set; }
        public string ModuleId { get; set; }
        public string icon { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
        public bool IsActive { get; set; }

        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }

    }
}
