//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDR
    {
        public int id { get; set; }
        public string Submerchantid { get; set; }
        public Nullable<decimal> basemdr { get; set; }
        public Nullable<decimal> tspmdr { get; set; }
        public string mdrtype { get; set; }
        public Nullable<System.DateTime> fromdate { get; set; }
        public Nullable<System.DateTime> todate { get; set; }
        public Nullable<bool> is_active { get; set; }
    }
}
