//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class merchant
    {
        public decimal id { get; set; }
        public string merchantid { get; set; }
        public string merchantname { get; set; }
        public byte[] merchantlogo { get; set; }
        public string activactionkey { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public string updatedby { get; set; }
        public string isdeleted { get; set; }
        public string headmerchantid { get; set; }
        public string UserType { get; set; }

        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }
    }
}
