
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;

    public partial class NDAApp
    {

        public string LoginEmailID { get; set; }
        public string VendorCode { get; set; }
        public string EstablishmentName { get; set; }
        public string OfficeAddress { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string PurchasingOrgName { get; set; }
        public string PurchasingOrgCode { get; set; }

        public string BankCountry { get; set; }
        public DateTime MinorityIndicatorDate { get; set; }

        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }


       


    }
}

