

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;

    public partial class PurchaseOrder
    {
        
        public int POId { get; set; }
        public string PONum { get; set; }
        public int POQtnId { get; set; }
        public int POStatus { get; set; }
        public int POOverallStatus { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedDtm { get; set; }
        public int ModifyBy { get; set; }
        public DateTime ModifyDtm { get; set; }

        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }
    }
}


