
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;

    public partial class Quotation
    {

        public int QtnId { get; set; }
        public int QtnPindId { get; set; }
        public string QtnNum { get; set; }
        public int QtnStatus { get; set; }
        public int QtnVndId { get; set; }
        public int QtnOrgId { get; set; }
        public int QtnOverallStatus { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedDtm { get; set; }
        public int ModifyBy { get; set; }
        public DateTime ModifyDtm { get; set; }
        public string QtnFilenm { get; set; }
        public string QtnFilenmSaved { get; set; }

        public string LoginEmailID { get; set; }      
        public string ContactPerson { get; set; }
        public DateTime QtnDate { get; set; }
        public int QtnNumber { get; set; }
        public string Remarks { get; set; }


        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }
    }
}


