

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;

    public partial class References
    {
        //public int TabIndex { get; set; }
        public string LoginEmailID { get; set; }
        //References
        public string RefCustomersName { get; set; }
        public string RefContactPerson { get; set; }
        public string RefDesignation { get; set; }
        public string RefContactNo { get; set; }
        public string RefEmailID { get; set; }



        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }
    }
}


