



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;

    public partial class Remark
    {

        public string VendorCode { get; set; }
        public string FieldId { get; set; }
        public string Remarks { get; set; }

        public Boolean Flag { get; set; }
        public string CreatedBy { get; set; }
        public string Status { get; set; }


        //public string LoginEmailID { get; set; }

        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }
    }
}
