//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;

    public partial class SAPMaster
    {
        //Input parameter
        public string ModeFlag { get; set; }


        public string BANKS { get; set; }

        //public string EKORG { get; set; }
        public string QLAND1 { get; set; }
        //public string QLAND { get; set; }
        //public string WITHT { get; set; }
        public string WITHTExemption { get; set; }
        public string vendorcode { get; set; }





        //Output parameter

        public int BUKRS { get; set; }
        public string EKORG { get; set; }
        public string EKOTX { get; set; }

        public int MANDT { get; set; }
        public string BANKL { get; set; }
        public string BANKA { get; set; }

        public string SAKNR { get; set; }
        public string TXT50 { get; set; }

        public string ZTERM { get; set; }
        public string TEXT1 { get; set; }

        public string ZLSCH { get; set; }
        public string TEXT2 { get; set; }

        public string ZAHLS { get; set; }
        public string TEXTL { get; set; }

        public string HBKID { get; set; }
        //public string BANKL { get; set; }

        public string KALSK { get; set; }
        public string KALSB { get; set; }

        //public string ZTERM { get; set; }
        //public string TEXT1 { get; set; }

        public string QLAND { get; set; }
        public string QLTXT { get; set; }

        public int GST_ID { get; set; }
        public string VEN_CLASS { get; set; }


        public string WITHT { get; set; }
        public string TEXT40 { get; set; }

        public string WT_WITHCD { get; set; }
        //public string TEXT40 { get; set; }

        public string LAND1 { get; set; }
        public string QSREC { get; set; }

        //public string BUKRS { get; set; }
        public string FIWTIN_SECOG { get; set; }


        //public string WITHT { get; set; }
        // public string TEXT40 { get; set; }

        //public string WT_WITHCD { get; set; }
        //public string TEXT40 { get; set; }

        public string WAERS { get; set; }
        public string LTEXT { get; set; }

        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }
    }
}

