//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;

    public partial class SAPobj
    {
  
        public string venderSapcode { get; set; }

        public string message { get; set; }

        public string msgtype { get; set; }
        public string msgdesc { get; set; }
        public string showmsg { get; set; }
        public string showmsgdesc { get; set; }
    }
}
