
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;
    public partial class Signup
    {
        public string InviteID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Designation { get; set; }
        public string MobileNo { get; set; }
        public string EmailAddress { get; set; }
        //public string OTP { get; set; }
        public string PreferredUserID { get; set; }
        public string Password { get; set; }
        //public string ConfirmPassword { get; set; }
        //public Boolean Active { get; set; }

        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }
    }
}
