//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submerchant_Master
    {
        public decimal Relation_ID { get; set; }
        public string ACQ_Name { get; set; }
        public string ACQ_Address { get; set; }
        public decimal ACQ_City { get; set; }
        public decimal ACQ_Pin_Code { get; set; }
        public string ACQ_Contact_No { get; set; }
        public bool Status { get; set; }
        public string Alias { get; set; }
    }
}
