//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submerchant_Form_Status
    {
        public decimal Relation_ID { get; set; }
        public string Title { get; set; }
        public bool Status { get; set; }
        public bool Default { get; set; }
        public bool Mandatory { get; set; }
        public decimal Ordering { get; set; }
        public decimal Status_Type { get; set; }
    }
}
