//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submerchant_Form_Field
    {
        public decimal Relation_ID { get; set; }
        public decimal Section { get; set; }
        public decimal Type { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
        public bool Required { get; set; }
        public string Placeholder { get; set; }
        public string Tooltip { get; set; }
        public bool Mandatory { get; set; }
        public bool Status { get; set; }
        public string Mask { get; set; }
        public string CssClass { get; set; }
        public string Additional { get; set; }
        public decimal Ordering { get; set; }
        public string ContainerCssClass { get; set; }
        public string Pattern { get; set; }
        public bool HasData { get; set; }
    }
}
