//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubMenu()
        {
            this.ScreenRoleMappings = new HashSet<ScreenRoleMapping>();
        }
    
        public int ID { get; set; }
        public string varScreenTitle { get; set; }
        public string varPageName { get; set; }
        public Nullable<int> MainMenuId { get; set; }
        public Nullable<decimal> Intorderno { get; set; }
        public Nullable<decimal> ServicesId { get; set; }
        public string AngularUrl { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScreenRoleMapping> ScreenRoleMappings { get; set; }


        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }

    }
}
