//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submerchant_Form_Section
    {
        public decimal Relation_ID { get; set; }
        public string SectionName { get; set; }
        public string SectionTitle { get; set; }
        public string SectionDescription { get; set; }
        public bool Status { get; set; }
        public decimal Ordering { get; set; }
        public string Icon { get; set; }
        public bool Document { get; set; }
    }
}
