//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submerchant
    {
        public decimal Id { get; set; }
        public string HeadMerchantID { get; set; }
        public string Submerchantid { get; set; }
        public string Submerchantshortid { get; set; }
        public string merchantid { get; set; }
        public string tollname { get; set; }
        public string Submerchanttype { get; set; }
        public string pricemode { get; set; }
        public string settlementtype { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public string createdby { get; set; }
        public string isdeleted { get; set; }


        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }
    }
}
