//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submerchantfaremapping
    {
        public decimal id { get; set; }
        public string submerchantid { get; set; }
        public string Vehicle_type { get; set; }
        public Nullable<decimal> Faretype { get; set; }
        public Nullable<decimal> Fareamount { get; set; }
        public Nullable<bool> isactive { get; set; }
        public string Updatedby { get; set; }
        public System.DateTime Updateddate { get; set; }
    }
}
