
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;

    public partial class TTLUse
    {
        public string VendorCode { get; set; }
        public string EKORG { get; set; }
        public string BANKL { get; set; }
        public string AKONT { get; set; }
        public string ZTERM { get; set; }
        public string ZWELS { get; set; }

        public string ZAHLS { get; set; }
        public string HBKID { get; set; }
        public string KALSK { get; set; }
        public string ZTERMComp { get; set; }
        public string QLAND { get; set; }

        public string VEN_CLASS { get; set; }
        public string IBAN { get; set; }
        public string J_1TPBUPL { get; set; }
        public string SWIFT { get; set; }

        public string BKONT { get; set; }
        public string BVTYP { get; set; }
        public string BANKTYPE { get; set; }

        public DateTime CERDT { get; set; }

        public string REPRF { get; set; }
        public string WEBRE { get; set; }
        public string XNBWY { get; set; }
        public string LEBRE { get; set; }
        public string CreatedBy { get; set; }




        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }


    }
}
