
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;

    public partial class VendorSAP
    {

        public string VendorCode { get; set; }

        public string Ekorg { get; set; }
        public string Lifnr { get; set; }
        public string Land1 { get; set; }
        public string Name1 { get; set; }
        public string Ort01 { get; set; }

        public string Pstlz { get; set; }
        public string Regio { get; set; }
        public string Sort1 { get; set; }
        public string Stras { get; set; }
        public string Anred { get; set; }

        public string StrSuppl1 { get; set; }
        public string Stcd1 { get; set; }
        public string Telf2 { get; set; }
        public string Stcd3 { get; set; }
        public string Stceg { get; set; }

        public string Stenr { get; set; }
        public string Banks { get; set; }
        public string Bankl { get; set; }
        public string Bankn { get; set; }
        public string Bkont { get; set; }

        public string Bkref { get; set; }
        public string Koinh { get; set; }
        public string SmtpAddr1 { get; set; }
        public string SmtpAddr2 { get; set; }
        public string SmtpAddr3 { get; set; }

        public string SmtpAddr4 { get; set; }
        public string SmtpAddr5 { get; set; }
        public string Akont { get; set; }
        public string Mindk { get; set; }
        public string Cerdt { get; set; }

        public string Zterm { get; set; }
        public string Reprf { get; set; }
        public string Zsabe { get; set; }
        public string Waers { get; set; }
        public string Kalsk { get; set; }

        public string Webre { get; set; }
        public string Xnbwy { get; set; }
        public string Lebre { get; set; }
        public string ZtermComp { get; set; }
        public string VenClass { get; set; }

        public string J1tpbupl { get; set; }
        public string Name2 { get; set; }
        public string TelNumber { get; set; }
        public string FaxNumber { get; set; }
        public string Iban { get; set; }

        public string BankType { get; set; }
        public string Swift { get; set; }
        public string Zuawa { get; set; }
        public string Zwels { get; set; }
        public string Zahls { get; set; }

        public string Hbkid { get; set; }
        public string Qland { get; set; }
        public string HouseNum1 { get; set; }
        public string StrSuppl2 { get; set; }
        public string StrSuppl3 { get; set; }


        //
        public string LoginEmailID { get; set; }
        


        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }
    }
}




