
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;

    public partial class Vendor
    {
        public int TabIndex { get; set; }
        public string LoginEmailID { get; set; }
        //Info
        //public int Vendor_Id { get; set; }
        //public string Vendor_Code { get; set; }
        public string GSTIN { get; set; }
        public string PANNo { get; set; }
        public string VATRegistration { get; set; }
        public string TaxNumber { get; set; }
        public string Country { get; set; }
        public string Title { get; set; }
        public string OrganisationType { get; set; }
        public string EstablishmentName { get; set; }
        //public string OrgTypeName { get; set; }
        public string ShortName { get; set; }
        public string NoofEmployees { get; set; }
        public string CompUrl { get; set; }
        public string CompEmailID { get; set; }
        public string HouseNo { get; set; }
        public string OfficeAddress { get; set; }
        public string Street2 { get; set; }
        public string Street3 { get; set; }
        public string RegState { get; set; }
        public string RegCity { get; set; }
        public string RegPostalCode { get; set; }
        public string CompTelephoneNo { get; set; }

        public string CompMobileNo { get; set; }
        public string FaxNo { get; set; }
        public string SupplierType { get; set; }

        //Bank Info
       
        public string BankCountry { get; set; }
        public string Currency { get; set; }
        public string BeneficiaryName { get; set; }
        public string BeneficiaryAccountNo { get; set; }
        public string BankName { get; set; }
        public string BeneficiaryBranch { get; set; }
        public string BeneficiaryAddress { get; set; }
        public string AccountType { get; set; }
        public string IFSCCode { get; set; }
        public string SWIFTBICCode { get; set; }

        //Fin Info

        public DateTime RegistrationDate { get; set; }
        public string FinancialYear1 { get; set; }
        public string FinancialYear2 { get; set; }
        public string FinancialYear3 { get; set; }
        public decimal Profit1 { get; set; }
        public decimal Profit2 { get; set; }
        public decimal Profit3 { get; set; }
        public decimal Turnover1 { get; set; }
        public decimal Turnover2 { get; set; }
        public decimal Turnover3 { get; set; }
        public string OnlineCatalog { get; set; }
        public string OnlineOrdering { get; set; }
        public string OnlineOrderTracking { get; set; }
        public string OnlineEauctions { get; set; }
        //public string MinorityIndicatorName { get; set; }
        public string MINDK { get; set; }
        public DateTime MinorityIndicatorDate { get; set; }

        //Legal Structure(Certification)
        public string ISO9001 { get; set; }     
        public DateTime DateISO9001 { get; set; }
        public string ISO27001 { get; set; }      
        public DateTime DateISO27001 { get; set; }
        public string C9100 { get; set; }       
        public DateTime DateC9100 { get; set; }
        public string QMSAvailableAtTheSuppliersSite { get; set; }
        public string EnvironmentManagementSystem { get; set; }
        public string WorkersCompensationInsurancePolicy { get; set; }
        public string OwnSuppliersAndSubContractors { get; set; }
        public string PublicLiabilityInsurancePolicy { get; set; }
        public string SupplierDueDiligenceRequirements { get; set; }
        public string IndemnityInsurancePolicy { get; set; }
        public string QualityEnvironmentalStandards { get; set; }


        //References
        public string RefCustomersName { get; set; }
        public string RefContactPerson { get; set; }
        public string RefDesignation { get; set; }
        public string RefContactNo { get; set; }
        public string RefEmailID { get; set; }


        //TTL Affiliation(Additional)
        public string MOB { get; set; }
        public string WOB { get; set; }
        public string VOB { get; set; }
        public string LGBTOB { get; set; }
        public string SDVOB { get; set; }
        public string SB { get; set; }
        public string SDB { get; set; }
        public string WOSB { get; set; }
        public string HUSB { get; set; }
        public string VOSB { get; set; }
        public string SDVOSB { get; set; }
        public string EDWOSB { get; set; }
        public string MBE { get; set; }
        public string DBE { get; set; }
        public string SBE { get; set; }
        public string SWAM { get; set; }
        public string LGBT { get; set; }
        public string SupplyAnyOtherTTL { get; set; }
        public string NameofCompanies { get; set; }
        public string TypeofWorkDone { get; set; }


        //NDA App
        public string VendorCode { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string PurchasingOrgName { get; set; }
        public string PurchasingOrgCode { get; set; }

        //ddl
        public string CountryName { get; set; }
        public string TitleName { get; set; }
        public string OrganisationTypeName { get; set; }
        public string RegStateName { get; set; }
        public string BankCountryName { get; set; }
        public string CurrencyName { get; set; }
        public string AccountTypeName { get; set; }
        public string MinorityIndicatorName { get; set; }

        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }


        


    }
}

