
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;

    public partial class WithholdingTax
    {

        public string VendorCode { get; set; }
        public string Ekorg { get; set; }
        public string WITHT { get; set; }
        public string WT_WITHCD { get; set; }
        public string QSREC { get; set; }

        public string WITHTTEXT { get; set; }
        public string WT_WITHCDTEXT { get; set; }
        public string QSRECTEXT { get; set; }
        public string CreatedBy { get; set; }

        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }
    }
}
