
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerSupplier.DataTransferObject
{
    using System;
    using System.Collections.Generic;

    public partial class WithholdingTaxExe
    {
        public string VendorCode { get; set; }
        public string Ekorg { get; set; }
        public string SECCODE { get; set; }
        public string WT_EXNR { get; set; }
        public decimal WT_EXRT { get; set; }
        public DateTime WT_EXDF { get; set; }
        public DateTime WT_EXDT { get; set; }
        public string WT_WTEXRS { get; set; }
        public string WITHT { get; set; }
        public string WT_WITHCD { get; set; }
        public decimal FIWTIN_EXEM_THR { get; set; }
        public string WAERS { get; set; }

        public string SECCODETEXT { get; set; }
        public string WITHTTEXT { get; set; }
        public string WT_WITHCDTEXT { get; set; }
        public string WAERSTEXT { get; set; }

        public string CreatedBy { get; set; }

        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public string MODE { get; set; }
    }
}